# Generated by Django 5.0.2 on 2024-02-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('AUD', models.FloatField()),
                ('AZN', models.FloatField()),
                ('GBP', models.FloatField()),
                ('AMD', models.FloatField()),
                ('BYN', models.FloatField()),
                ('BGN', models.FloatField()),
                ('BRL', models.FloatField()),
                ('HUF', models.FloatField()),
                ('VND', models.FloatField()),
                ('HKD', models.FloatField()),
                ('GEL', models.FloatField()),
                ('DKK', models.FloatField()),
                ('AED', models.FloatField()),
                ('USD', models.FloatField()),
                ('EUR', models.FloatField()),
                ('EGP', models.FloatField()),
                ('INR', models.FloatField()),
                ('IDR', models.FloatField()),
                ('KZT', models.FloatField()),
                ('CAD', models.FloatField()),
                ('QAR', models.FloatField()),
                ('KGS', models.FloatField()),
                ('CNY', models.FloatField()),
                ('MDL', models.FloatField()),
                ('NZD', models.FloatField()),
                ('NOK', models.FloatField()),
                ('PLN', models.FloatField()),
                ('RON', models.FloatField()),
                ('XDR', models.FloatField()),
                ('SGD', models.FloatField()),
                ('TJS', models.FloatField()),
                ('THB', models.FloatField()),
                ('TRY', models.FloatField()),
                ('TMT', models.FloatField()),
                ('UZS', models.FloatField()),
                ('UAH', models.FloatField()),
                ('CZK', models.FloatField()),
                ('SEK', models.FloatField()),
                ('CHF', models.FloatField()),
                ('RSD', models.FloatField()),
                ('ZAR', models.FloatField()),
                ('KRW', models.FloatField()),
                ('JPY', models.FloatField()),
            ],
        ),
    ]
